---
title: "Download packages and files"
output: html_document
urlcolor: blue
---

<style type="text/css">
.main-container {
  max-width: 90% !important;
  margin: auto;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

## Primary packages {.tabset}

### Benthic package
<a href="https://github.com/shgroves/NCRMP_benthics" target="_blank" style="color:blue"> Benthic R Package GitHub</a>

<br><br>

### Fish package
<a href="https://github.com/jeremiaheb/rvc" target="_blank" style="color:blue"> Fish R Package GitHub</a>

<br><br><br>


## Graph/plotting scripts {.tabset}

<!-- To add a download link, use the following format:

<details><summary><a href="path/to/file" download style="color:blue">Download ____</a></summary>
DETAILS:
<li>blah blah</li>
</details>

NOTE: All fish files should be in the folder fish_plots, and all benthic files should be in XXXXX. Both zip files should be remade when R scripts are added to the folders, and a note should be made at the top of updates.RMD with the date.
-->

<details><summary>If you have customized previously downloaded scripts...</summary>

When downloading R scripts to source, be aware that if you have previously downloaded scripts and edited them that you can overwrite any changes by downloading all files as a zip. <br>
It is reccomended to only download files you do not already have downloaded, especially if you have made edits.

</details> <br>

### All benthic files
TO BE ADDED

### Individual benthic files
TO BE ADDED

### All fish files
<details><summary><a href="./fish_plots/fish-files.zip" download style="color:blue">Download all files</a></summary>

Includes: <br>
<li>WrapperFunctions.</li>
<li>theme_publication.R</li>
<li>QL_SubregionDensityPlot.R</li>
<li>QL_binned_LengthFreq.</li>
<li>plot_horizontal_bar_shared_axis.R</li>
<li>labeler.R  

</details> <br>

### Indivisual fish files
<details><summary><a href="./fish_plots/WrapperFunctions.R" download style="color:blue">WrapperFunctions.R</a></summary>

Requires the following files to run: <br>
<li>theme_publication.R</li>

</details> <br>
<details><summary><a href="./fish_plots/theme_publication.R" download style="color:blue">theme_publication.R</a></summary>

Requires the following files to run: <br>
<li>N/A</li>

</details> <br>
<details><summary><a href="./fish_plots/QL_SubregionDensityPlot.R" download style="color:blue">QL_SubregionDensityPlot.R</a></summary>

Requires the following files to run: <br>
<li>theme_publication.R</li>

</details> <br>
<details><summary><a href="./fish_plots/QL_binned_LengthFreq.R" download style="color:blue">QL_binned_LengthFreq.R</a></summary>

Requires the following files to run: <br>
<li>labeler.R</li>
<li>theme_publication.R</li>

</details> <br>
<details><summary><a href="./fish_plots/plot_horizontal_bar_shared_axis.R" download style="color:blue">plot_horizontal_bar_shared_axis.R</a></summary>

Requires the following files to run: <br>
<li>N/A</li>

</details> <br>
<details><summary><a href="./fish_plots/labeler.R" download style="color:blue">labeler.R</a></summary>

Requires the following files to run: <br>
<li>N/A</li>

</details> <br>

