---
title: "&nbsp;"
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: false
    toc_depth: 3
    code_folding: hide
---
# **Fish: Length frequency**
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE, message=FALSE,warning=FALSE,class.source = 'fold-show'}
library(rvc)
library(tidyverse)
source("fish_plots/theme_publication.R")
source("fish_plots/labeler.R")
source("fish_plots/WrapperFunctions.R")
source("fish_plots/QL_binned_LengthFreq.R")
source("fish_plots/QL_SubregionDensityPlot.R")
source("fish_plots/plot_horizontal_bar_shared_axis.R")
#this block is invisible
#add any sources or packages needed for figures below
```

<br>

<!-- 
All figures are made using the species Ocyurus chrysurus (OCY CHRY) 
-->

## Load data
```{r data, message=FALSE,warning=FALSE,class.source = 'fold-show'}
keys11_14 = getRvcData(years = 2011:2014, regions = c("FLA KEYS"))
torts12_16 = getRvcData(years = 2012:2016, regions = c("DRY TORT"))
```

<br>

## Plots

<!-- To add another figure set:
### Figure type title {.tabset}

#### Defaults
'''{r example, warning=FALSE,message=FALSE,error=FALSE,results='hold', fig.keep='all'}
  #include function call here - only include required parameters
  #be sure to list all parameters with descriptive comments
'''

#### Alt
'''{r example, warning=FALSE,message=FALSE,error=FALSE,results='hold', fig.keep='all'}
  #include function call here - include all parameters
  #be sure to list all parameters with descriptive comments
'''

Defaults and alt are not necessarily required, but please include at least 2 variations of the figure.

When the figure is added, save the image of one of the variations to the folder labeled "home-figs" and add it to the home page linking to the figure
-->

### Fork length frequency comparison {.tabset}
#### Defaults
```{r flf.d, warning=FALSE,message=FALSE,error=FALSE,results='hide', fig.keep='all'}
plot_domain_LF_by_year(data = keys11_14, #required 
                       species = "ocy chry", #required 
                       bin_size = 5, #required
                       vertical_line = NULL, #add vertical (dashed) line
                       title = NULL) #add a figure title
```

#### Alt
```{r flf.a, warning=FALSE,message=FALSE,error=FALSE,results='hide', fig.keep='all'}
plot_domain_LF_by_year(data = keys11_14, #required 
                       species = "ocy chry", #required 
                       bin_size = 3, #required
                       vertical_line = NULL,  #add vertical (dashed) line
                       title = expression(paste(italic("Ocyurus chrysurus"), #Allows scientific name to be italicized
                                                " in the Florida Keys")))
```
