---
title: "&nbsp;"
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: false
    toc_depth: 3
    code_folding: hide
---

# **Fish: Single year plots**
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE, message=FALSE,warning=FALSE,class.source = 'fold-show'}
library(rvc)
library(tidyverse)
source("fish_plots/theme_publication.R")
source("fish_plots/labeler.R")
source("fish_plots/WrapperFunctions.R")
source("fish_plots/QL_binned_LengthFreq.R")
source("fish_plots/QL_SubregionDensityPlot.R")
source("fish_plots/plot_horizontal_bar_shared_axis.R")
#this block is invisible
#add any sources or packages needed for figures below
```

<br>

<!-- 
All figures are made using the species Ocyurus chrysurus (OCY CHRY) 
-->

## Load data
```{r data, message=FALSE,warning=FALSE,class.source = 'fold-show'}
keys11_14 = getRvcData(years = 2011:2014, regions = c("FLA KEYS"))
torts12_16 = getRvcData(years = 2012:2016, regions = c("DRY TORT"))
```

<br>

## Plots

<!-- To add another figure set (the #s control the headers):
### Figure type title {.tabset}

#### Defaults
```{r example, warning=FALSE,message=FALSE,error=FALSE,results='hold', fig.keep='all'}
  #include function call here - only include required parameters
  #be sure to list all parameters with descriptive comments
```

#### Alt
```{r example2, warning=FALSE,message=FALSE,error=FALSE,results='hold', fig.keep='all'}
  #include function call here - include all parameters
  #be sure to list all parameters with descriptive comments
```

Defaults and alt are not necessarily required, but please include at least 2 variations of the figure.

When the figure is added, save the image of one of the variations to the folder labeled "home-figs" and add it to the home page linking to the figure
-->

### Top N density of subregion {.tabset}

#### Top 10
```{r top10, warning=FALSE,message=FALSE,error=FALSE,results='hide', fig.keep='all'}
plotSubregionDens(df1 = keys11_14, #required
                  yr = 2011, #required
                  topOcc_n = 10) #required; number of spp to include
```
<br><br>

#### Top 25
```{r top25, warning=FALSE,message=FALSE,error=FALSE,results='hide', fig.keep='all'}
plotSubregionDens(df1 = torts12_16, #required
                  yr = 2012, #required
                  topOcc_n = 25) #required; number of spp to include
```
<br><br>

### Species occurrence vs CV of Density {.tabset}

#### Florida Keys 2011
```{r svcv.fl11, warning=FALSE,message=FALSE,error=FALSE,results='hide', fig.keep='all', fig.width=10, fig.height=6}
plot_cv_vs_occurrence(df = keys11_14,
                      yr = 2011,
                      plotTitle = "Floriday Keys, 2011")
```
<br><br>

#### Dry Tortugas 2014
```{r svcv.dt14, warning=FALSE,message=FALSE,error=FALSE,results='hide', fig.keep='all', fig.width=10, fig.height=6}
plot_cv_vs_occurrence(df = torts12_16,
                      yr = 2014,
                      plotTitle = "Dry Tortugas, 2014")
```
<br><br>
